[build]
  command = "pip install -r requirements.txt"
  publish = "functions"

[functions]
  pythonVersion = "3.11"

[functions.environment]
  AWS_ACCESS_KEY_ID1 = "${AWS_ACCESS_KEY_ID1}"
  AWS_SECRET_ACCESS_KEY1 = "${AWS_SECRET_ACCESS_KEY1}"
  UNSTRUCTURED_API_KEY = "${UNSTRUCTURED_API_KEY}"
  SUPABASE_PASSWORD = "${SUPABASE_PASSWORD}"
  FLASK_ENV = "production"
  FLASK_DEBUG = "0"
