# Exported from Render on 2024-11-23T04:03:01Z
services:
- type: web
  name: fastunstructpostgres
  runtime: python
  repo: https://github.com/KevinDyerAU/fastunstructapi
  plan: starter
  region: singapore
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn src.main:app --timeout 240
  autoDeploy: false
version: "1"
