# FastUnstructAPI Render Configuration
# Python 3.12.3 is recommended for best compatibility

services:
- type: web
  name: fastunstructapi
  runtime: python
  repo: https://github.com/KevinDyerAU/fastunstructapi
  plan: standard  # Upgraded to standard for better performance
  region: singapore
  buildCommand: |
    pip install -r requirements.txt
  startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker src.main:app --timeout 240
  
  # Python and application settings
  envVars:
    - key: PYTHON_VERSION
      value: 3.12.3
    - key: PYTHONUNBUFFERED
      value: true
    - key: PYTHONDONTWRITEBYTECODE
      value: 1
    - key: PYTHONFAULTHANDLER
      value: 1
    - key: LOG_LEVEL
      value: INFO
    - key: DEBUG
      value: false
  
  # AWS Configuration
  envVars:
    - key: AWS_ACCESS_KEY_ID
      fromService:
        name: fastunstructapi
        type: web
        property: env.AWS_ACCESS_KEY_ID
    - key: AWS_SECRET_ACCESS_KEY
      fromService:
        name: fastunstructapi
        type: web
        property: env.AWS_SECRET_ACCESS_KEY
    - key: AWS_SESSION_TOKEN  # For temporary credentials if needed
      fromService:
        name: fastunstructapi
        type: web
        property: env.AWS_SESSION_TOKEN
      optional: true
    - key: AWS_REGION
      value: ap-southeast-2
  
  # Unstructured.io Configuration
  envVars:
    - key: UNSTRUCTURED_API_KEY
      fromService:
        name: fastunstructapi
        type: web
        property: env.UNSTRUCTURED_API_KEY
    - key: UNSTRUCTURED_API_URL
      value: https://api.unstructured.io
  
  # Supabase Configuration
  envVars:
    - key: SUPABASE_HOST
      value: aws-0-ap-southeast-2.pooler.supabase.com
    - key: SUPABASE_PORT
      value: "5432"
    - key: SUPABASE_USERNAME
      fromService:
        name: fastunstructapi
        type: web
        property: env.SUPABASE_USERNAME
    - key: SUPABASE_PASSWORD
      fromService:
        name: fastunstructapi
        type: web
        property: env.SUPABASE_PASSWORD
    - key: SUPABASE_DATABASE
      value: postgres
    - key: SUPABASE_TABLE
      value: elements
  
  # Deployment settings
  autoDeploy: true
  healthCheckPath: /
  numInstances: 2  # Increased for better availability
  disk:
    name: data
    mountPath: /data
    sizeGB: 1  # Small disk for logs and temporary files
  
  # Resource allocation
  resources:
    memory: 1GB
    cpu: 1.0

# Required for Render
version: "1"
